apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ${{ secrets.ACR_NAME }}.azurecr.io/my-app:v1  # ACR image URL
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: azure-registry-secret  # O nome do secret criado anteriormente
