name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # O pipeline será acionado em pushs para a branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Images
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

        for service in $(ls -d */ | grep -E 'Service|API'); do
          # Remover a barra final do nome do diretório
          service_name=$(echo $service | sed 's/\/$//')

        # Converter para lowercase
        service_name_lower=$(echo $service_name | tr '[:upper:]' '[:lower:]')

          # Verificar se o Dockerfile existe
          if [ -f "$service/Dockerfile" ]; then
            echo "Building and pushing $service_name_lower"
            cd $service
            docker build -t ${{ secrets.ACR_NAME }}/${service_name_lower}:v1 .
            docker push ${{ secrets.ACR_NAME }}/${service_name_lower}:v1
            cd ..
          else
            echo "Skipping $service_name_lower: Dockerfile not found."
          fi
        done

    - name: Set Kubernetes Context
      uses: azure/aks-set-context@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Deploy to AKS
      run: |
        for service in $(ls -d */ | grep -E 'Service|API'); do
          kubectl apply -f $service/deployment.yaml
        done
